export const SHOW_PROCESS_MANAGER_MODAL_TYPES = {
  DUPLICATE_PROCESS: 'DUPLICATE_PROCESS',
  IMPORT_NEW_PROCESS: 'IMPORT_NEW_PROCESS',
  IMPORT_AND_REPLACE_PROCESS: 'IMPORT_AND_REPLACE_PROCESS',
};

export const PROCESS_VISIBILITY = {
  ORGANIZATION: 'ORGANIZATION',
  USER_SPECIFIC: 'USER_SPECIFIC',
};
