export const PROCESS_HISTORY_STATUSES = {
  ACTIVE: 'ACTIVE',
  REJECT: 'REJECT',
  BUFFER: 'BUFFER',
  FALLOUT: 'FALLOUT',
};

export const PROCESS_HISTORY_STATUS_LABEL_MAP = {
  [PROCESS_HISTORY_STATUSES.ACTIVE]: 'Active',
  [PROCESS_HISTORY_STATUSES.REJECT]: 'Reject',
  [PROCESS_HISTORY_STATUSES.BUFFER]: 'Buffer',
  [PROCESS_HISTORY_STATUSES.FALLOUT]: 'Fallout',
};

export const PROCESS_HISTORY_STATUS_DESCRIPTION_MAP = {
  [PROCESS_HISTORY_STATUSES.ACTIVE]: 'Execute processes normally',
  [PROCESS_HISTORY_STATUSES.REJECT]: 'Prevent new executions',
  [PROCESS_HISTORY_STATUSES.BUFFER]: 'Hold new executions until next Active status',
  [PROCESS_HISTORY_STATUSES.FALLOUT]: 'Prevent new executions and create fallout tickets',
};

export const PROCESS_HISTORY_STATUS_MENU_OPTIONS = [
  {
    label: PROCESS_HISTORY_STATUS_LABEL_MAP[PROCESS_HISTORY_STATUSES.ACTIVE],
    value: PROCESS_HISTORY_STATUSES.ACTIVE,
    description: PROCESS_HISTORY_STATUS_DESCRIPTION_MAP[PROCESS_HISTORY_STATUSES.ACTIVE],
  },
  {
    label: PROCESS_HISTORY_STATUS_LABEL_MAP[PROCESS_HISTORY_STATUSES.BUFFER],
    value: PROCESS_HISTORY_STATUSES.BUFFER,
    description: PROCESS_HISTORY_STATUS_DESCRIPTION_MAP[PROCESS_HISTORY_STATUSES.BUFFER],
  },
  {
    label: PROCESS_HISTORY_STATUS_LABEL_MAP[PROCESS_HISTORY_STATUSES.FALLOUT],
    value: PROCESS_HISTORY_STATUSES.FALLOUT,
    description: PROCESS_HISTORY_STATUS_DESCRIPTION_MAP[PROCESS_HISTORY_STATUSES.FALLOUT],
  },
  {
    label: PROCESS_HISTORY_STATUS_LABEL_MAP[PROCESS_HISTORY_STATUSES.REJECT],
    value: PROCESS_HISTORY_STATUSES.REJECT,
    description: PROCESS_HISTORY_STATUS_DESCRIPTION_MAP[PROCESS_HISTORY_STATUSES.REJECT],
  },
];

export const PROCESS_HISTORY_STATUS_COLOR_MAP = {
  [PROCESS_HISTORY_STATUSES.ACTIVE]: 'darkGrassGreen',
  [PROCESS_HISTORY_STATUSES.REJECT]: 'venetianRed',
  [PROCESS_HISTORY_STATUSES.BUFFER]: 'burntYellow',
  [PROCESS_HISTORY_STATUSES.FALLOUT]: 'burntYellow',
};
