export const EVENT_TRIGGER_FILTER_KEYS = {
  ENVIRONMENT_IDS: 'environmentIds',
  WORKFLOWS_in_USE: 'workflowsInUse',
  CREATED_AT: 'createdAt',
  UPDATED_AT: 'updatedAt',
};

export const EVENT_TRIGGERS_SIDE_FILTER_INITIAL_VALUES = {
  [EVENT_TRIGGER_FILTER_KEYS.UPDATED_AT]: '',
  [EVENT_TRIGGER_FILTER_KEYS.CREATED_AT]: '',
  [EVENT_TRIGGER_FILTER_KEYS.WORKFLOWS_in_USE]: '',
  [EVENT_TRIGGER_FILTER_KEYS.ENVIRONMENT_IDS]: null,
};

export const FILTERS_FORM_KEY = 'sideFilter';
