export const PHONE_NUMBER_MANAGEMENT_TYPES = {
  INPUT: 'input',
  TABLE: 'table',
  AVAILABLE: 'available',
  ALL: 'all',
};

export const PHONE_NUMBER_VARIANTS = {
  WITH_NO_PROCESS_OR_AGENTS: 'WITH_NO_PROCESS_OR_AGENTS',
  WITH_PROCESS_AND_AGENTS: 'WITH_PROCESS_AND_AGENTS',
  WITH_ONLY_AGENTS: 'WITH_ONLY_AGENTS',
  WITH_ONLY_PROCESSES: 'WITH_ONLY_PROCESSES',
  WITH_PROCESS_AND_AGENTS_BUT_NO_AVAILABLE: 'WITH_PROCESS_AND_AGENTS_BUT_NO_AVAILABLE',
};

export const LOCATION_VALUES = {
  REGION: 'region',
  PROVINCE: 'province',
  COUNTRY: 'country'
}