export const singleProcessInvalidDataStrings = Object.freeze({
  INVALID_FIELD_TOAST: 'Please fill the field correctly',
  ALPHANUMERIC_VALIDATION: 'Please enter valid letters or numbers',
  ALPHABET_VALIDATION: 'Please enter valid letters',
  EMAIL_VALIDATION: 'Please enter a valid email',
  PHONE_NUMBER_VALIDATION: 'Please enter a valid 10 digits phone number',
  NUMBER_VALIDATION: 'Please enter valid numbers',
  ADDRESS_VALIDATION: 'Please enter valid address',
  GENERIC_VALIDATION: 'Please enter input',
  DATE_OF_BIRTH_VALIDATION: 'Please enter a valid date',
  POSTAL_CODE_VALIDATION: 'Please enter a valid postal code',
  FILE_UPLOAD: 'Please upload the file',
});

export const singleProcessPlaceholderStrings = Object.freeze({
  INVALID_FIELD_TOAST: 'Please fill the field correctly',
  BOOLEAN_VALIDATION: 'Enter a boolean, ex - True',
  ALPHANUMERIC_VALIDATION: 'Enter valid letters or numbers,  ex - Abc123',
  ALPHABET_VALIDATION: 'Enter valid letters, ex - Abc',
  EMAIL_VALIDATION: 'Enter email, ex - abc@domain.com',
  PHONE_NUMBER_VALIDATION: 'Enter phone number, ex - 0000000000',
  NUMBER_VALIDATION: 'Enter numbers, ex- 12345',
  ADDRESS_VALIDATION: 'Enter address, ex- 123, main street',
  GENERIC_VALIDATION: 'Enter Input, ex - Abc, 123',
  DATE_OF_BIRTH_VALIDATION: 'Enter date',
  POSTAL_CODE_VALIDATION: 'Enter postal code, ex - AAA 000',
  FILE_UPLOAD: 'Please upload the file',
});

export const singleExecutionModalKeys = Object.freeze({
  STRING: {
    value: 'STRING',
  },
  NUMBER: {
    value: 'NUMBER',
    text: singleProcessInvalidDataStrings.NUMBER_VALIDATION,
    placeholderText: singleProcessPlaceholderStrings.NUMBER_VALIDATION,
    dataTypeLabel: 'Number',
    inputExample: '12345',
  },
  ADDRESS: {
    value: 'ADDRESS',
    text: singleProcessInvalidDataStrings.ADDRESS_VALIDATION,
    placeholderText: singleProcessPlaceholderStrings.ADDRESS_VALIDATION,
    dataTypeLabel: 'String (Letters/Numbers)',
    inputExample: 'Abc, 123',
  },
  GENERIC: {
    value: 'GENERIC',
    text: singleProcessInvalidDataStrings.GENERIC_VALIDATION,
    placeholderText: singleProcessPlaceholderStrings.GENERIC_VALIDATION,
    dataTypeLabel: 'String',
    inputExample: 'John, 123.',
  },
  PHONE_NUMBER: {
    value: 'PHONE_NUMBER',
    text: singleProcessInvalidDataStrings.PHONE_NUMBER_VALIDATION,
    placeholderText: singleProcessPlaceholderStrings.PHONE_NUMBER_VALIDATION,
    dataTypeLabel: 'Phone Number',
    inputExample: '(123)-456-7890',
  },
  EMAIL: {
    value: 'EMAIL',
    text: singleProcessInvalidDataStrings.EMAIL_VALIDATION,
    placeholderText: singleProcessPlaceholderStrings.EMAIL_VALIDATION,
    dataTypeLabel: 'Email',
    inputExample: 'abc@email.com',
  },
  ALPHA_NUMERIC: {
    value: 'ALPHA_NUMERIC',
    text: singleProcessInvalidDataStrings.ALPHANUMERIC_VALIDATION,
    placeholderText: singleProcessPlaceholderStrings.ALPHANUMERIC_VALIDATION,
    dataTypeLabel: 'String (Letters/Numbers)',
    inputExample: 'Abcdef 123',
  },
  ALPHABET: {
    value: 'ALPHABET',
    text: singleProcessInvalidDataStrings.ALPHABET_VALIDATION,
    placeholderText: singleProcessPlaceholderStrings.ALPHABET_VALIDATION,
    dataTypeLabel: 'String (Letters)',
    inputExample: 'John',
  },
  DATE_OF_BIRTH: {
    value: 'DATE_OF_BIRTH',
    text: singleProcessInvalidDataStrings.DATE_OF_BIRTH_VALIDATION,
    placeholderText: singleProcessPlaceholderStrings.DATE_OF_BIRTH_VALIDATION,
    dataTypeLabel: 'Date of Birth',
    inputExample: '2000-12-30',
  },
  POSTAL_CODE: {
    value: 'POSTAL_CODE',
    text: singleProcessInvalidDataStrings.POSTAL_CODE_VALIDATION,
    placeholderText: singleProcessPlaceholderStrings.POSTAL_CODE_VALIDATION,
    dataTypeLabel: 'Postal Code',
    inputExample: 'ABC 123',
  },
  BOOLEAN: {
    value: 'BOOLEAN',
    text: singleProcessInvalidDataStrings.INVALID_FIELD_TOAST,
    placeholderText: singleProcessPlaceholderStrings.BOOLEAN_VALIDATION,
    dataTypeLabel: 'Boolean',
    inputExample: 'true',
  },
  FILE: {
    value: 'FILE',
    text: singleProcessInvalidDataStrings.FILE_UPLOAD,
    placeholderText: singleProcessPlaceholderStrings.FILE_UPLOAD,
    dataTypeLabel: 'File',
  },
  M: 'M',
  RED_BORDER_COLOR: 'rgb(238, 56, 56)',
  REMOVE_RED_BORDER_COLOR: 'rgba(217, 217, 217, 1)',
  FIELD_INPUT: 'fieldsInput',
});
