export default Object.freeze({
  DEFAULT: '/',
  LOCKED_ACCOUNT: '/lockedAccount',
  YOUR_ANALYTICS: '/YourAnalytics',
  CHAT: '/LiveChat',
  TICKETS: '/Tickets',
  TICKETS_FULLVIEW: '/Tickets/:ticketId',
  FALLOUT_TICKETS: '/falloutTickets',
  FALLOUT_TICKETS_FULL_VIEW: '/falloutTickets/:falloutTicketId',
  EXECUTION_HISTORY: '/executionHistory',
  BOA_DASHBOARD: '/boaDashboard',
  BOA_DASHBOARD_PROCESS_VIEW: '/boaDashboard/:workflowName',
  CONVERSE_DASHBOARD: '/converse/dashboard',
  PROCESS_HISTORY: '/processHistory',
  PROCESS_HISTORY_BULK_PREVIEW: '/processHistory/bulkPreview/:ticketId',
  FRONT_OFFICE: '/FrontOffice',
  REGISTER: '/register',

  AGENT_CONNECTOR: '/AgentConnector',
  AGENT_CONNECTOR_DETAILS: '/AgentConnector/bot/:botId',
  AGENT_CONNECTOR_WIDGETS: '/AgentConnector/ChatWidgets',
  AGENT_CONNECTOR_WIDGETS_DETAILS: '/AgentConnector/ChatWidgets/:widgetId',
  AGENT_CONNECTOR_WIDGETS_CREATE: '/AgentConnector/ChatWidgets/Customizer/CreateChatWidget',
  AGENT_CONNECTOR_WIDGETS_EDIT: '/AgentConnector/ChatWidgets/Customizer/CreateChatWidget/:widgetId',
  AGENT_CONNECTOR_ENTRY_AGENTS: '/AgentConnector/EntryAgents',
  AGENT_CONNECTOR_ENTRY_AGENTS_DETAILS: '/AgentConnector/EntryAgents/:entryAgentId',
  PROJECTS: '/Projects',
  PROJECTS_1: '/Projects/:projectId',
  PEOPLE: '/People',
  PERSON_FULLVIEW: '/People/:personId',

  TEST_DASHBOARD: '/test/dashboard',
  TEST_HISTORY: '/test/history',
  CATALOG: '/Catalog',
  CATALOG_MODULE: '/Catalog/CatalogModule',
  CATALOG_MODULE_DETAILS: '/Catalog/CatalogModule/:catalogModuleId',
  CATALOG_CATEGORY: '/Catalog/Category',
  CATALOG_CATEGORY_DETAILS: '/Catalog/Category/:CategoryId',
  CATALOG_PRODUCT_OFFERING_PRICE: '/Catalog/ProductOfferingPrice',
  CATALOG_PRODUCT_OFFERING_PRICE_DETAILS: '/Catalog/ProductOfferingPrice/:productOfferingPriceId',
  CATALOG_PRODUCT_SPECIFICATION: '/Catalog/ProductSpecification',
  CATALOG_PRODUCT_SPECIFICATION_DETAILS: '/Catalog/ProductSpecification/:productSpecificationId',
  CATALOG_IMPORT_JOB: '/Catalog/ImportJob',
  CATALOG_IMPORT_JOB_DETAILS: '/Catalog/ImportJob/:importJobId',
  CATALOG_EXPORT_JOB: '/Catalog/ExportJob',
  CATALOG_EXPORT_JOB_DETAILS: '/Catalog/ExportJob/:exportJobId',
  CATALOG_NOTIFICATION_LISTENER: '/Catalog/NotificationListeners',
  CATALOG_NOTIFICATION_LISTENER_DETAILS: '/Catalog/NotificationListeners/:listenerId',
  CATALOG_EVENTS_SUBSCRIPTION: '/Catalog/EventsSubscription',
  CATALOG_EVENTS_SUBSCRIPTION_DETAILS: '/Catalog/EventsSubscription/:subscriptionId',
  CATALOG_PRODUCT_OFFERING: '/Catalog/ProductOffering',
  CATALOG_PRODUCT_OFFERING_DETAILS: '/Catalog/ProductOffering/:productId',
  SETTINGS: '/Settings',
  SETTINGS_SERVICES: '/Settings/Agents',
  SETTINGS_ACCESS_MANAGER: '/Settings/AccessManagement',
  SETTINGS_ACCESS_MANAGER_USER_DETAILS: '/Settings/AccessManagement/users/:id',
  SETTINGS_ACCESS_MANAGER_USER_CHANGE_PASSWORD: '/Settings/AccessManagement/users/:id/changePassword',
  SETTINGS_ACCESS_MANAGER_EDIT_USER: '/Settings/AccessManagement/users/:id/edit',
  SETTINGS_ACCESS_MANAGER_USERS: '/Settings/AccessManagement/users',
  SETTINGS_ACCESS_MANAGER_PERMISSION_GROUPS: '/Settings/AccessManagement/permissionGroups',
  SETTINGS_ACCESS_MANAGER_PERMISSION_GROUP_DETAILS: '/Settings/AccessManagement/permissionGroups/:id',
  SETTINGS_SERVICES_PREFIX: '/Services',
  SETTINGS_SERVICES_DETAILS: '/Services/:serviceId',
  SETTINGS_CHANNELS: '/Settings/Channels',
  SETTINGS_USER_MANAGEMENT: '/Settings/UserManagement',
  SETTINGS_PAGE_PERMISSIONS: '/Settings/PagePermissions',
  SETTINGS_PERMISSION_GROUPS: '/Settings/PermissionGroups',
  SETTINGS_CONFIGURATION_PROFILE: '/Settings/ConfigurationProfile',
  SETTINGS_AGENT_SKILLS: '/Settings/UserSkills',
  SETTINGS_AGENT_SKILL_TYPES: '/Settings/UserSkillTypes',
  SETTINGS_USER_GROUPS: '/Settings/AccessManagement/userGroups',
  SETTINGS_USER_GROUPS_SINGLE_ITEM: '/Settings/AccessManagement/userGroups/:id',
  SETTINGS_INTEGRATIONS: '/Settings/Integrations',
  SETTINGS_NOTIFICATIONS: '/Settings/Notifications',
  SETTINGS_NOTIFICATION_RULES: '/Settings/NotificationRules',
  SETTINGS_AGENT_CATEGORIES: '/Settings/AgentCategories',
  SETTINGS_REPORTING: '/Settings/Reporting',
  SETTINGS_USER_UNBOARDING: '/Settings/UserOnboarding',

  SETTINGS_GENERAL_TAB: '/Settings/General',
  SETTINGS_GENERAL_TAB_CREATE_KNOWLEDGE_BASE: '/Settings/General/CreateKnowledgeBase',
  SETTINGS_GENERAL_TAB_EDIT_KNOWLEDGE_BASE: '/Settings/General/EditKnowledgeBase/:knowledgeBaseId',
  SETTINGS_USERS_TAB: '/Settings/Users',
  SETTINGS_FRONT_OFFICE_TAB: '/Settings/FrontOffice',
  SETTINGS_BACK_OFFICE_TAB: '/Settings/BackOffice',
  SETTINGS_USAGE_TAB: '/Settings/Usage',
  SETTINGS_BILLING_TAB: '/Settings/Billing',

  SETTINGS_CREATE_SERIVCE_TICKET_TYPE: '/Settings/FrontOffice/CreateServiceTicketType',
  SETTINGS_EDIT_SERIVCE_TICKET_TYPE: '/Settings/FrontOffice/EditServiceTicketType/:id',
  SETTINGS_CREATE_CHAT_WIDGET: '/Settings/FrontOffice/createChatWidget',
  SETTINGS_EDIT_CHAT_WIDGET: '/Settings/FrontOffice/editChatWidget/:id',
  SETTINGS_EDIT_CHAT_WIDGET_WITHOUT_ID: '/Settings/FrontOffice/editChatWidget',

  SETTINGS_CREATE_PARAMETER_SET: '/Settings/BackOffice/ParameterSet',
  SETTINGS_EDIT_PARAMETER_SET: '/Settings/BackOffice/ParameterSet/:id',

  SUPPORT: '/Support',
  PROFILE: '/Profile',
  PROFILE_CHANGE_PASSWORD: '/Profile/changePassword',
  PROFILE_EDIT: '/Profile/edit',
  UNAUTHORIZED: '/Unauthorized',
  FORGOT_PASSWORD: '/ForgotPassword',
  CREATE_ACCOUNT: '/CreateNewAccount',
  RESET_PASSWORD: '/ResetPassword',
  FILES: '/FileManager',
  CONVERSATION_HISTORY: '/ConversationHistory',
  PROCESS_ORCHESTRATION: '/ProcessOrchestrator',
  PROCESS_ORCHESTRATION_DETAILS: '/ProcessOrchestrator/:processId',
  PROCESS_ORCHESTRATION_EDIT: '/ProcessOrchestrator/:processId/edit',
  PROCESS_ORCHESTRATION_HISTORY: '/ProcessOrchestrator/:processId/history/:executingId',
  PROCESS_TRIGGER: '/ProcessTrigger',
  EVENT_TRIGGER_DETAILS: '/ProcessTrigger/EventTrigger',
  EVENT_TRIGGER_DETAILS_EDIT: '/ProcessTrigger/EventTrigger/:id',
  PROCESS_DATA_VISUALIZER: '/ProcessDataVisualizer',

  // MANAGERS
  AGENT_MANAGER: '/AgentManager',
  AGENT_MANAGER_DIAGRAM: '/AgentManager/:serviceTypeId',

  PROCESS_MANAGER: '/ProcessManager',
  PROCESS_MANAGER_INFO: '/flow/editor/:processId',
  PROCESS_MANAGER_SPREADSHEET: '/ProcessManager/:processId/:taskId/spreadsheet',
  TEST_MANAGER: '/test/manager',
  TEST_SUITE_DETAILS: '/test/suite/:suiteId',
  TEST_CASE_DETAILS: '/test/case/:caseId',
  TEST_GROUP_DETAILS: '/test/group/:groupId',
  TEST_EDITOR: '/test/editor',
  TEST_EDITOR_INFO: '/test/editor/:testCaseId',
  MR_MANAGER: '/Migrate/manager',
  MR_HISTORY: '/Migrate/history',
  MR_MANAGER_MAPPING_EDITOR: '/Migrate/manager/:MappingEditorId',
  CUSTOMER_MANAGER: '/Sell/CustomerManager',
  CUSTOMER_PROFILE: '/Sell/CustomerManager/:CustomerId',
  ORDER_MANAGER: '/Sell/OrderManager',
  PRODUCT_ORDER_HISTORY_DETAILS: '/Sell/OrderManager/:orderId',
  PRODUCT_OFFERINGS: '/Sell/OrderManager/ProductOfferings',
  PRODUCT_OFFERINGS_CHECKOUT: '/Sell/OrderManager/ProductOfferings/Checkout',
  PRODUCT_OFFERINGS_CONFIRMATION: '/Sell/OrderManager/ProductOfferings/Confirmation',
});

export const navLinkTitles = {
  PROJECTS: 'Projects',
  DASHBOARD: 'Dashboard',
  BOA_DASHBOARD: 'BOA Dashboard',
  BOA_DASHBOARD_LOWER_CASE: '/boaDashboard/',
  BOA_DASHBOARD_LOWER_CASE_TITLE: 'boaDashboard',
  WORKFLOW_NAME: '/:workflowName',
};

export const modifyTitlesKeysENUM = { UNDERSCORE: '_' };

export const accountDisabledKeys = {
  USER_DISABLED: 'to your user account being cancelled by the Symphona team',
  SUBSCRIPTION_AUTO_CANCELLED: 'to your user account being cancelled by the Symphona team',
};
