export const FREQUENCY_TYPES = {
  ONE_MINUTE: '1 min',
  THIRTY_MINUTE: '30 min',
  HOURLY: 'Hourly',
  DAILY: 'Daily',
  MONTHLY: 'Monthly',
  YEARLY: 'Yearly',
};

export const FREQUENCY_TYPE_VALUES = {
  [FREQUENCY_TYPES.ONE_MINUTE]: '1min',
  [FREQUENCY_TYPES.THIRTY_MINUTE]: '30min',
  [FREQUENCY_TYPES.HOURLY]: '1hour',
  [FREQUENCY_TYPES.DAILY]: 'daily',
  [FREQUENCY_TYPES.MONTHLY]: 'monthly',
  [FREQUENCY_TYPES.YEARLY]: 'yearly',
};

export const TIME_RANGE_TYPES = {
  TODAY: 'TODAY',
  THIS_WEEK: 'THIS_WEEK',
  LAST7DAYS: 'last7days',
  LAST30DAYS: 'last30days',
  LAST90DAYS: 'last90days',
  LAST365DAYS: 'last365days',
  THIS_MONTH: 'THIS_MONTH',
  THIS_YEAR: 'THIS_YEAR',
  ALLDAYS: 'alldays',
  CUSTOM: 'CUSTOM',
};

export const CONVERSE_DASHBOARD_FILTER_TYPE_KEYS = {
  CONVERSATIONAL: 'CONVERSATIONAL',
  SERVICE_TICKET_OVERVIEW: 'SERVICE_TICKET_OVERVIEW',
  SERVICE_TICKET: 'SERVICE_TICKET',
  SERVICE_TICKET_TASK: 'SERVICE_TICKET_TASK',
};

export const CONVERSE_DASHBOARD_FILTER_USE_FORMIK_KEYS = {
  MAIN: {
    TIME_FRAME: 'timeFrame',
    FREQUENCY: 'frequency',
  },
  SETTINGS: {
    CHANNELS: 'channels',
    BAR_OR_LINE_GRAPH: 'barOrLineGraph',
    NUMBER_OR_PERCENTAGE_GRAPH: 'view',
    SHOW_INDIVIDUAL_CHANNEL: 'showIndividualChannels',
    SHOW_INDIVIDUAL_CHANNEL_POSITION_1: 'p1',
    SHOW_INDIVIDUAL_CHANNEL_POSITION_2: 'p2',
    SHOW_MOVING_AVERAGE: 'showMovingAverage',
  },
  SIDE_FILTERS: {
    AGENTS: 'agents',
    AGENT_TAGS: 'agentTags',
    ASSIGNED_AGENTS: 'assignedAgents',
    PROCESS_ALL_PROCESSES: 'processAllProcesses',
    PROCESS_TAGS: 'processTags',
    IVA_ALL_AGENTS: 'ivaAllAgents',
    IVA_AGENT_TAGS: 'ivaAgentTags',
    SHOW_MANUALLY_GENERATED_TICKETS: 'showManuallyGeneratedTickets',
  },
};

export const FILTER_KEYS_SIDE_FILTERS_SERVICE_TICKETS = [
  CONVERSE_DASHBOARD_FILTER_USE_FORMIK_KEYS.SIDE_FILTERS.ASSIGNED_AGENTS,
  CONVERSE_DASHBOARD_FILTER_USE_FORMIK_KEYS.SIDE_FILTERS.PROCESS_ALL_PROCESSES,
  CONVERSE_DASHBOARD_FILTER_USE_FORMIK_KEYS.SIDE_FILTERS.PROCESS_TAGS,
  CONVERSE_DASHBOARD_FILTER_USE_FORMIK_KEYS.SIDE_FILTERS.IVA_ALL_AGENTS,
  CONVERSE_DASHBOARD_FILTER_USE_FORMIK_KEYS.SIDE_FILTERS.IVA_AGENT_TAGS,
  CONVERSE_DASHBOARD_FILTER_USE_FORMIK_KEYS.SIDE_FILTERS.SHOW_MANUALLY_GENERATED_TICKETS,
];

export const FILTER_KEYS_SIDE_FILTERS_CONVERSATIONAL = [
  CONVERSE_DASHBOARD_FILTER_USE_FORMIK_KEYS.SIDE_FILTERS.AGENTS,
  CONVERSE_DASHBOARD_FILTER_USE_FORMIK_KEYS.SIDE_FILTERS.AGENT_TAGS,
];

export const BAR_OR_LINE_GRAPH_TYPES = {
  BAR_GRAPH: 'BAR_GRAPH',
  LINE_GRAPH: 'LINE_GRAPH',
};

export const NUMBER_OR_PERCENTAGE_GRAPH_TYPES = {
  NUMBER: 'NUMBER',
  PERCENTAGE: 'PERCENTAGE',
};

export const CHART_SIDE_FILTER_KEY = 'sideFilter';

export const PROCESS_DEFINITIONS = 'PROCESS_DEFINITIONS';

export const ISSUE_CATEGORY_IDS = {
  [CONVERSE_DASHBOARD_FILTER_TYPE_KEYS.SERVICE_TICKET]: 1,
  [CONVERSE_DASHBOARD_FILTER_TYPE_KEYS.SERVICE_TICKET_TASK]: 2,
};

const getFilterKey = (title) => title.split(/\s/).join('_').toUpperCase();

export const CONVERSATIONS_LOCAL_STORAGE_KEYS = {
  DASHBOARD: getFilterKey('Conversation Dashboard'),
  CONVERSATIONS: getFilterKey('Conversations'),
  AVG_LENGTH: getFilterKey('Average Conversations Length'),
  TRANSFERRED: getFilterKey('Transferred Conversations'),
};

export const SERVICE_TICKET_LOCAL_STORAGE_KEYS = {
  SERVICE_TICKET_DASHBOARD: getFilterKey('Service Ticket Dashboard'),
  OPEN_AND_RESOLVED: getFilterKey('Open & Resolved Tickets'),
  AVG_TICKET_RESOLUTION_TIME: getFilterKey('Average Ticket Resolution Time'),
  OPEN_AND_RESOLVED_TASKS: getFilterKey('Open & Resolved Ticket Tasks'),
  AVG_TICKET_TASK_AND_RESOLUTION_TIME: getFilterKey('Average Ticket Task Resolution Time'),
};

export const CONVERSATIONS_LEGEND_LABELS = [{ value: 'duration', label: 'Amount of conversation' }];
