export const USER_IDENTIFICATION_BLOCK = {
  RADIO_INPUT_LABEL: {
    UPON_TRANSFER_REQUEST: 'UPON_TRANSFER_REQUEST',
    UPON_START_OF_CONVERSION: 'UPON_START_OF_CONVERSATION',
    NEVER_COLLECT: 'NEVER_COLLECT'
  },
  COLLECT_FIRST_NAME_STRING: 'collectFirstName',
  COLLECT_FULL_NAME_STRING: 'collectFullName',
  COLLECT_LAST_NAME_STRING: 'collectLastName'
}