export const EXPANDED_TYPES = {
  SERVICE_TICKET_TYPE: 'SERVICE_TICKET_TYPE',
  CHAT_WIDGETS: 'CHAT_WIDGETS',
  PHONE_NUMBER: 'PHONE_NUMBER',
  DEFAULT_AGENT: 'DEFAULT_AGENT'
}

export const CREATE_EDIT_TABS = {
  GENERAL_SETTINGS: 'GENERAL_SETTINGS',
  AGENTS: 'AGENTS',
  APPEARANCE: 'APPEARANCE'
}
