/* eslint-disable no-unused-vars */
export const customStyles = {
  control: (style, state) => ({
    ...style,
    cursor: 'pointer',
    border: state.isDisabled ? '1px solid #969CA3' : '1px solid #2D3A47',
    borderColor: state.isDisabled ? '#969CA3' : '#2D3A47',
    backgroundColor: '#FFFFFF',
    boxShadow: 'none',
    outline: 'none',
    borderRadius: '100px',
    fontSize: '16px',
    fontWeight: '400',
    color: state.isDisabled ? '#808080' : '#2D3A47',
    padding: '6px 16px',
    transition: 'background 200ms ease-in-out',
    '&:hover': {
      borderColor: state.isDisabled ? '#969CA3' : '#2D3A47',
    },
  }),
  valueContainer: (style) => ({
    ...style,
    color: '#2D3A47',
  }),
  indicatorsContainer: (style) => ({
    ...style,
    alignSelf: 'stretch',
  }),
  dropdownIndicator: (style, state) => ({
    ...style,
    transform: state.selectProps.menuIsOpen ? 'rotate(-180deg)' : 'rotate(0deg)',
    transition: 'transform 200ms ease',
    color: state.isDisabled ? '#969CA3' : '#2D3A47',
  }),
  indicatorSeparator: (style, state) => ({
    ...style,
    width: '1.5px',
    margin: '0 6px 0 0',
    backgroundColor: state.isDisabled ? '#808080' : '#2D3A47',
    alignSelf: 'stretch',
  }),
  menu: (style) => ({
    ...style,
    // left: '-50%',
    display: 'flex',
    width: '100%',
    background: '#FFFFFF',
    boxShadow: '1px 1px 10px 2px rgba(0, 0, 0, 0.1)',
    borderRadius: '10px',
    padding: '6px',
  }),
  menuList: (style) => ({
    ...style,
    flex: '1 1 auto',
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
    fontWeight: '400',
    fontSize: '16px',
    padding: '16px 6px 16px 8px',
    overflow: 'overlay',
    '::-webkit-scrollbar': {
      width: ' 8px',
      height: '8px',
      background: 'transparent',
    },
    ':hover::-webkit-scrollbar-thumb': {
      border: '3px solid rgba(255, 255, 255, 0.2)',
      borderRadius: '10px',
      background: 'rgba(198, 198, 198, 0.75)',
    },
    ':hover::-webkit-scrollbar-track': {
      borderRadius: '2px',
      background: 'transparent',
    },
    ':hover::-webkit-scrollbar-track-piece:': {
      borderRadius: '2px',
      outline: '2px solid #c6c6c6',
      background: ' rgba(242, 242, 242, 0.8)',
      margin: '0',
      marginBottom: '1px',
    },
  }),
  option: () => ({
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
    cursor: 'pointer',
    flexWrap: 'wrap',
    borderRadius: '5px',
    padding: '8px',
    marginRight: '6px',
    color: '#000000',
    fontSize: '16px',
    fontWeight: '400',
    transition: 'background 200ms ease-in-out',
    '&:hover': {
      background: 'rgba(45, 58, 71, 0.2)',
    },
  }),
};
