export const PUBLIC_FORM_QUERY_KEYS = {
  GET_PUBLIC_FORM_CONFIG: 'GET_PUBLIC_FORM_CONFIG',
};

export const PUBLIC_FORM_THEME_VALUES = {
  LIGHT: 'LIGHT',
  DARK: 'DARK',
};

export const PUBLIC_FORM_IMAGE_TYPES = {
  FORM_LOGO: 'FORM_LOGO',
  BG_IMAGE: 'BG_IMAGE',
};
