export const ORCHESTRATOR_RECENT_EXECUTIONS_INITIAL_VALUES = {
  updatedAfter: '',
  updatedBefore: '',
  createdAtAfter: '',
  createdAtBefore: '',
};

export const EXECUTIONS_STATUSES = {
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
  EXECUTING: 'EXECUTING',
  CANCELLED: 'CANCELLED',
  SCHEDULED: 'SCHEDULED',
  PREPARING: 'PREPARING',
};

export const EXECUTIONS_STATUS_MAP = {
  [EXECUTIONS_STATUSES.EXECUTING]: 'Executing',
  [EXECUTIONS_STATUSES.SUCCESS]: 'Success',
  [EXECUTIONS_STATUSES.FAILED]: 'Failed',
  [EXECUTIONS_STATUSES.SCHEDULED]: 'Scheduled',
  [EXECUTIONS_STATUSES.CANCELLED]: 'Canceled',
  [EXECUTIONS_STATUSES.PREPARING]: 'Preparing',
};

export const ORCHESTRATOR_GROUP_EXECUTIONS_STATUS_COLOR_MAP = {
  [EXECUTIONS_STATUSES.EXECUTING]: 'burntYellow',
  [EXECUTIONS_STATUSES.PREPARING]: 'burntYellow',
  [EXECUTIONS_STATUSES.SUCCESS]: 'savingsGreen',
  [EXECUTIONS_STATUSES.FAILED]: 'venetianRed',
  [EXECUTIONS_STATUSES.CANCELLED]: 'linkWater',
};
