export const PRODUCT_ORDERS_FILTER_KEY = 'sideFilter';

export const PRODUCT_FILTERS = {
  NAME_REGEX: 'nameRegex',
  DESCRIPTION_REGEX: 'descriptionRegex',
  IS_BUNDLE: 'isBundle',
  CATEGORY: 'category',
  SORT_BY: 'sortBy',
  SORT_DIRECTION: 'sortDirection',
  LIMIT: 'limit',
  FIELDS: 'fields',
  OFFSET: 'offset',
  IS_SELLABLE: 'isSellable',
  VALID_TO: 'validTo',
  VALID_FROM: 'validFrom',
  NAME: 'name',
  DESCRIPTION: 'description',
  PRODUCT_OFFERING_ID: 'productOfferingId',
  SORT_ORDER: 'sortOrder',
  IS_ASCENDING: 'isAscending',
  IS_ROOT: 'isRoot',
  LOCALE: 'locale',
  PRODUCT_OFFERING_CATEGORY_IDS: 'productOfferingCategoryIds',
  SHIPPING_ADDRESS_ROLE: 'shippingAddress',
  BILLING_ADDRESS_ROLE: 'billingAddress',
  SERVICE_ADDRESS_ROLE: 'serviceAddress',
  CUSTOMER: 'customer',
  CUSTOMER_NAME: 'customerName',
  CUSTOMER_ID: 'customerId',
  ID: 'id',
  STATUS: 'status',
  ORDER_DATE: 'orderDate',
  PRICE: 'price',
  PHONE_NUMBER: 'phone',
  EMAIL: 'email',
  BAN: 'billingAccount',
  RELATED_PARTY_ID: 'relatedPartyId',
  FIRST_NAME: 'firstName',
  LAST_NAME: 'lastName',
  ORDER_START_DATE: 'requestedStartDate',
  ORDER_END_DATE: 'requestedEndDate',
  STATE: 'state',
  PURCHASE_DATE: 'purchasedDate',
  PURCHASE_BEFORE: 'purchasedBefore',
  PURCHASE_AFTER: 'purchasedAfter',
  ESTIMATED_DELIVERY_DATE: 'expectedCompletionDate',
  CREATED_DATE: 'dateCreated',
  PRODUCT_PRICE: 'productPrice',
  STREET_NAME: 'streetName',
  PROVINCE: 'province',
  CITY: 'city',
  POSTAL_CODE: 'postCode',
  COUNTRY: 'country',
  COST_CENTER_ID: 'costCenterId',
  ORGANIZATION: 'orgName',
  ROLE: 'role',
  TITLE: 'title',
  ESCALATION_CONTACT_1: 'escalationContact1',
  ESCALATION_CONTACT_2: 'escalationContact2',
  ESCALATION_CONTACT_3: 'escalationContact3',
  ESCALATION_CONTACT_4: 'escalationContact4',
  ESCALATION_CONTACT_5: 'escalationContact5',
  USER_ID: 'userId',
  PASSWORD: 'password',
  EXTERNAL_ID: 'externalId',
  DEPARTMENT: 'departmentName',
  BADGE_NUMBER: 'badgeNumber',
  USERNAME: 'userName',
  EXTERNAL_ORG_ID: 'externalOrgId',
  EXTERNAL_DEPARTMENT_ID: 'externalDepartmentId',
};

export const PRODUCT_OFFERINGS_INITIAL_VALUES = {
  [PRODUCT_FILTERS.NAME_REGEX]: '',
  [PRODUCT_FILTERS.DESCRIPTION_REGEX]: '',
  [PRODUCT_FILTERS.IS_BUNDLE]: true,
  [PRODUCT_FILTERS.CATEGORY]: '',
  [PRODUCT_FILTERS.SORT_BY]: '', // TODO: Replace this comment with sort options once BE is updated
  [PRODUCT_FILTERS.SORT_DIRECTION]: 'ASC', // 'ASC' | 'DESC'
  [PRODUCT_FILTERS.LIMIT]: 100,
};

export const DYNAMIC_PRODUCT_OFFERINGS_INITIAL_VALUES = {
  [PRODUCT_FILTERS.NAME_REGEX]: '',
  [PRODUCT_FILTERS.DESCRIPTION_REGEX]: '',
  [PRODUCT_FILTERS.IS_SELLABLE]: true,
  [PRODUCT_FILTERS.CATEGORY]: '',
  [PRODUCT_FILTERS.SORT_BY]: '',
  [PRODUCT_FILTERS.SORT_DIRECTION]: 'ASC', // 'ASC' | 'DESC'
  [PRODUCT_FILTERS.LIMIT]: 4,
};

export const PRODUCT_ORDERS_SIDE_FILTER_INITIAL_VALUES = {
  [PRODUCT_FILTERS.ORDER_DATE]: '',
  [PRODUCT_FILTERS.CUSTOMER]: '',
  [PRODUCT_FILTERS.CUSTOMER_ID]: '',
  [PRODUCT_FILTERS.STATUS]: [],
};

export const PRODUCT_ORDERS_INITIAL_VALUES = {
  [PRODUCT_ORDERS_FILTER_KEY]: PRODUCT_ORDERS_SIDE_FILTER_INITIAL_VALUES,
  [PRODUCT_FILTERS.ORDER_START_DATE]: '',
  [PRODUCT_FILTERS.ORDER_END_DATE]: '',
  [PRODUCT_FILTERS.CUSTOMER]: '',
  [PRODUCT_FILTERS.CUSTOMER_ID]: '',
  [PRODUCT_FILTERS.STATUS]: '',
};

export const PRODUCT_INVENTORY_SIDE_FILTER_INITIAL_VALUES = {
  [PRODUCT_FILTERS.PURCHASE_DATE]: '',
  [PRODUCT_FILTERS.STATUS]: [],
};

export const PRODUCT_INVENTORY_INITIAL_VALUES = {
  [PRODUCT_ORDERS_FILTER_KEY]: PRODUCT_INVENTORY_SIDE_FILTER_INITIAL_VALUES,
  [PRODUCT_FILTERS.STATUS]: [],
  [PRODUCT_FILTERS.PURCHASE_BEFORE]: '',
  [PRODUCT_FILTERS.PURCHASE_AFTER]: '',
  [PRODUCT_FILTERS.RELATED_PARTY_ID]: '',
};

export const PRODUCT_CREATE_CUSTOMER_INITIAL_VALUES = {
  [PRODUCT_FILTERS.FIRST_NAME]: '',
  [PRODUCT_FILTERS.LAST_NAME]: '',
  [PRODUCT_FILTERS.PHONE_NUMBER]: '',
  [PRODUCT_FILTERS.EMAIL]: '',
};

export const PRODUCT_GOA_NEW_CUSTOMER_INITIAL_VALUES = {
  ...PRODUCT_CREATE_CUSTOMER_INITIAL_VALUES,
  [PRODUCT_FILTERS.USERNAME]: '',
  [PRODUCT_FILTERS.PASSWORD]: '',
  [PRODUCT_FILTERS.TITLE]: '',
  [PRODUCT_FILTERS.ORGANIZATION]: '',
  [PRODUCT_FILTERS.DEPARTMENT]: '',
  [PRODUCT_FILTERS.ROLE]: '',
  [PRODUCT_FILTERS.BADGE_NUMBER]: '',
  [PRODUCT_FILTERS.EXTERNAL_ORG_ID]: '',
  [PRODUCT_FILTERS.EXTERNAL_DEPARTMENT_ID]: '',
  [PRODUCT_FILTERS.COST_CENTER_ID]: '',
  [PRODUCT_FILTERS.ESCALATION_CONTACT_1]: '',
  [PRODUCT_FILTERS.ESCALATION_CONTACT_2]: '',
  [PRODUCT_FILTERS.ESCALATION_CONTACT_3]: '',
  [PRODUCT_FILTERS.ESCALATION_CONTACT_4]: '',
  [PRODUCT_FILTERS.ESCALATION_CONTACT_5]: '',
  [PRODUCT_FILTERS.SHIPPING_ADDRESS_ROLE]: {
    [PRODUCT_FILTERS.STREET_NAME]: '',
    [PRODUCT_FILTERS.PROVINCE]: '',
    [PRODUCT_FILTERS.CITY]: '',
    [PRODUCT_FILTERS.POSTAL_CODE]: '',
    [PRODUCT_FILTERS.COUNTRY]: 'Canada',
  },
};
